// <auto-generated />
using System;
using Foyer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foyer.Core.Data.Migrations
{
    [DbContext(typeof(FoyerDbContext))]
    partial class FoyerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Foyer.Core.Domain.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CategoryOverridden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerHost")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LabelTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TagsOverridden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "SortOrder");

                    b.HasIndex("DockerHost", "ContainerName")
                        .IsUnique()
                        .HasFilter("\"DockerHost\" IS NOT NULL");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Foyer.Core.Domain.BookmarkTag", b =>
                {
                    b.Property<int>("BookmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("BookmarkId", "Tag");

                    b.ToTable("BookmarkTags");
                });

            modelBuilder.Entity("Foyer.Core.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystem = true,
                            Name = "Uncategorized",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Foyer.Core.Domain.Bookmark", b =>
                {
                    b.HasOne("Foyer.Core.Domain.Category", "Category")
                        .WithMany("Bookmarks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Foyer.Core.Domain.BookmarkTag", b =>
                {
                    b.HasOne("Foyer.Core.Domain.Bookmark", null)
                        .WithMany("UserTags")
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foyer.Core.Domain.Bookmark", b =>
                {
                    b.Navigation("UserTags");
                });

            modelBuilder.Entity("Foyer.Core.Domain.Category", b =>
                {
                    b.Navigation("Bookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
