<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Foyer.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foyer.Core\Foyer.Core.csproj" />
  </ItemGroup>

</Project>
